image: jupyter/minimal-notebook:x86_64-python-3.11.6

variables:
  SRC: ./src
  AWS_CLI_IMAGE: amazon/aws-cli:2.15.40

##
## Defined stages
##

stages:
  - build
  - deploy

##
## Install libraries and run notebook
##

build:
  stage: build
  script:
    - pip install -r $SRC/requirements.txt
    - find $SRC -name "*.ipynb" -exec jupyter execute {} \;
    - jupyter nbconvert --output-dir=./docs/$(basename "${file%.*}") --to html ./src/*.ipynb
  artifacts:
    paths:
    - ./docs/*

##
## Push to S3 Bucket
##

deploy:
  stage: deploy
  image:
    name: $AWS_CLI_IMAGE
    entrypoint: [""]
  variables:
    AWS_ACCESS_KEY_ID: $AWS_S3_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY: $AWS_S3_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION: eu-south-1
    BUCKET_PATH: s3://$BUCKET_NAME/
  script:
    - aws s3 cp docs/ $BUCKET_PATH --recursive
    - CONSOLE_URL="https://s3.console.aws.amazon.com/s3/buckets/${BUCKET_NAME}?region=${AWS_DEFAULT_REGION}"
    - echo "Path to generated S3 console URLs $CONSOLE_URL"
